# NumPy Arrays

In [1]:
#import numpy library
import numpy as np


In [2]:
#define your own list
my_list= [1,2,3]
my_list


[1, 2, 3]

In [3]:
#convert your list into the numpy array
np.array(my_list)


array([1, 2, 3])

In [4]:
#define your own matrix
my_matrix= [[1,2,3],[4,5,6],[7,8,9]]
my_matrix


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
#convert your matrix into the numpy array (use:arrange)
np.array(my_matrix)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
#Return evenly spaced values within a given interval
np.arange(0,10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#Generate arrays of zeros or ones
np.zeros(3)

array([ 0.,  0.,  0.])

In [9]:
#Return evenly spaced numbers over a specified interval (use:linspace)
np.linspace(0,10,3)


array([  0.,   5.,  10.])

In [10]:
#Creates an identity matrix (use:eye)
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [11]:
#Creates an array of the given shape and populates it with random samples from a uniform distribution over [0, 1) (use:rand)
np.random.rand(2)


array([ 0.69445779,  0.51841713])

In [12]:
#Returns a sample (or samples) from the "standard normal" distribution [σ = 1]. 
#Unlike rand which is uniform, values closer to zero are more likely to appear (use:randn)
np.random.randn(5,5)


array([[ 0.0382861 ,  1.16906069,  2.11204923, -0.64304352, -0.29099232],
       [ 0.11695004,  0.30101883,  0.60868309, -0.21508082,  1.03285808],
       [-0.91232957,  0.09507244, -0.45171246, -0.46585862,  0.09159324],
       [-0.74577168,  0.28948424,  1.76458858, -1.38190555, -1.12426541],
       [-0.7523147 ,  1.16780389,  1.04459026, -0.18321476,  0.43992111]])

In [15]:
#Returns random integers from low (inclusive) to high (exclusive) (use: randint)
np.random.randint(1,100)


35

In [17]:
#use these two lines of code
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [19]:
#change the shape of arr
arr.shape


(25,)

In [ ]:
#find min, max,index location of min and max


In [20]:
#find the data type of the arr
arr.dtype

dtype('int32')

# NumPy Indexing and Selection

In [21]:
#Creating sample array
arr = np.arange(0,11)
#show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
#Get a value at an index
arr[8]

8

In [23]:
#Get values in a range
arr[1:5]


array([1, 2, 3, 4])

In [25]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100
arr


array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [26]:
#Reset array, we'll see why I had to reset in  a moment

arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
#Important notes on Slices

slice_of_arr = arr[0:6]

#show

slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [28]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [ ]:
##########Now note the changes also occur in our original array!

In [29]:
#Data is not copied, it's a view of the original array! This avoids memory problems
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [30]:
#Indexing a 2D array (matrices)
#The general format is arr_2d[row][col] or arr_2d[row,col]. I recommend using the comma notation for clarity.

arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [31]:
#find the values for row index 1
arr_2d[1]

array([20, 25, 30])

In [32]:
#find the individual element value in row 1 and col0

arr_2d[1][0]

20

In [33]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]


array([[10, 15],
       [25, 30]])

In [34]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [35]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

# NumPy Operations

In [36]:
import numpy as np
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
#use diffrent operations for arr array
arr+arr


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [41]:
#Taking Square Roots

np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [42]:
#Calculating exponential (e^)
np.exp(arr)


array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [43]:
#Trigonometric Functions like sine
np.sin(arr)


array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [44]:
#Taking the Natural Logarithm
np.log(arr)


C:\Users\Amir\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458])

Axis Logic:

When working with 2-dimensional arrays (matrices) we have to consider rows and columns. This becomes very important when we get to the section on pandas. In array terms, axis 0 (zero) is the vertical axis (rows), and axis 1 is the horizonal axis (columns).

These values (0,1) correspond to the order in which arr.shape values are returned.


In [45]:
#use this numpy array
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [46]:
#get sum of axis 0
arr_2d.sum(axis=0)

array([15, 18, 21, 24])

In [47]:
# THINK ABOUT WHAT THIS WILL RETURN BEFORE RUNNING THE CELL!
arr_2d.sum(axis=1)

array([10, 26, 42])

# NumPy_Review_Exercises

In [48]:
#1. Import NumPy as np
import numpy as np

In [49]:
#2. Create an array of 10 zeros
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [50]:
#3. Create an array of 10 ones
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [51]:
#4. Create an array of 10 fives
np.ones(10) * 5

array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])

In [52]:
#5. Create an array of the integers from 10 to 50
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [53]:
#6. Create an array of all the even integers from 10 to 50
np.arange(10,51,2)


array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [54]:
#7. Create a 3x3 matrix with values ranging from 0 to 8
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [66]:
#8. Create a 3x3 identity matrix
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [55]:
#9. Use NumPy to generate a random number between 0 and 1
np.random.rand(1)

array([ 0.45439764])

In [56]:
#10. Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution
np.random.randn(25)

array([ 0.55809117, -2.10573122,  0.6622763 ,  0.23834908,  0.49569121,
       -1.53005147,  0.36655381,  0.13265207, -1.53825996,  0.41805315,
       -0.54189289, -1.60892719,  0.99863327,  1.37930878,  0.53722492,
        1.63446376,  0.71717429, -0.51192182, -0.77167715,  0.92759632,
        1.58605527, -0.09521345, -1.04114562,  0.34045773,  0.73770009])

In [57]:
#12. Create an array of 20 linearly spaced points between 0 and 1
np.linspace(0,1,20)

array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])

In [58]:
#Now you will be given a starting matrix (be sure to run the cell below!), 
#and be asked to replicate the resulting matrix outputs

# RUN THIS CELL - THIS IS OUR STARTING MATRIX
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [59]:
#13. Write code that reproduces the output shown below.
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [60]:
#14. Write code that reproduces the output 20.
mat[3,4]

20

In [61]:
#15. Write code that reproduces the output shown below.
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [ ]:
array([[ 2],
       [ 7],
       [12]])

In [62]:
#16. Write code that reproduces the output shown below.
mat[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [63]:
#18. Get the sum of all the values in mat
mat.sum()

325

In [64]:
#19. Get the standard deviation of the values in mat
mat.std()

7.2111025509279782

In [65]:
#20. Get the sum of all the columns in mat
mat.sum(axis=0)

array([55, 60, 65, 70, 75])